AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam-image-resizer

  Sample SAM Template for aws-sam-image-resizer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

Resources:


#*------DynamoDB table--------
  ThumbgenProccessImages:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String


#*---------S3 Buckets--------
  MyUploadsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-uploads-${AWS::Region}

  ProcessedRawImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-outputs-${AWS::Region}
 

#*-----------Layer-------
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: common-layer
      ContentUri: layers/common
      CompatibleRuntimes:
        - python3.14
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.14

 
#*-----------LambdaFunction---------
  ResizeImageHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: resize_image/
      Handler: app.resize_image_handler
      Layers: 
        - !Ref CommonLayer
      Environment:
        Variables:
          THUMBNAIL_SIZE: 128
          OUTPUT_BUCKET: !Ref ProcessedRawImageBucket
          TABLE_NAME: !Ref ThumbgenProccessImages
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${AWS::StackName}-uploads-${AWS::Region}
        - S3WritePolicy:
            BucketName: !Sub ${AWS::StackName}-outputs-${AWS::Region}
        - DynamoDBCrudPolicy:
            TableName: !Ref ThumbgenProccessImages
      Events:
        FileUploadEvent:
          Type: S3 # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Bucket: !Ref MyUploadsBucket
            Events: s3:ObjectCreated:*


  
Outputs:
  ResizeImageHandlerArn:
    Description: Resize image Lambda function ARN
    Value: !GetAtt ResizeImageHandler.Arn
  ResizeImageHandlerIamRoleArn:
    Description: Implicit IAM Role created for the resize function
    Value: !GetAtt ResizeImageHandlerRole.Arn
  UploadsBucketName:
    Value: !Ref MyUploadsBucket
  OutputsBucketName:
    Value: !Ref ProcessedRawImageBucket
  




